"""Build the SFZ files sfizz actually renders: build/sfz/<part>.sfz

    instruments/<part>.sfz   (ours, small, editable: attack / filter / vel curve)
  + sample-pack mapping       (pack's own .sfz, or regions generated from WAV names)
  = build/sfz/<part>.sfz      (flattened; our opcodes win, absolute sample paths)

Why flatten instead of `#include`?  In SFZ, opcodes on a <region>/<group> beat
the <global>, so a pack that sets ampeg_attack per region would silently ignore
our 0.28 s attack.  The flattener strips every opcode we override from the pack
and puts ours in the <global>, so instruments/*.sfz is always authoritative.

Run:  python -m src.render.sfz_prepare [part ...]
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

from src import config as C

NOTE_PC = {"c": 0, "d": 2, "e": 4, "f": 5, "g": 7, "a": 9, "b": 11}
HEADER_RE = re.compile(r"<(\w+)>")
OPCODE_RE = re.compile(r"([A-Za-z0-9_$]+)=")


# ------------------------------------------------------------------ parsing
def strip_comments(text: str) -> str:
    out = []
    for line in text.splitlines():
        i = line.find("//")
        out.append(line if i < 0 else line[:i])
    return "\n".join(out)


def preprocess(path: Path, root: Path, defines: dict[str, str]) -> str:
    """Resolve #include / #define recursively, return plain SFZ text."""
    text = strip_comments(path.read_text(errors="replace"))
    out = []
    for line in text.splitlines():
        s = line.strip()
        m = re.match(r'#define\s+(\$\w+)\s+(.+)', s)
        if m:
            defines[m.group(1)] = m.group(2).strip()
            continue
        m = re.match(r'#include\s+"([^"]+)"', s)
        if m:
            inc = m.group(1).replace("\\", "/")
            cand = [root / inc, path.parent / inc]
            target = next((c for c in cand if c.exists()), None)
            if target is None:
                print(f"[sfz] warning: include not found: {inc}")
                continue
            out.append(preprocess(target, root, defines))
            continue
        for k in sorted(defines, key=len, reverse=True):
            line = line.replace(k, defines[k])
        out.append(line)
    return "\n".join(out)


def parse_opcodes(body: str) -> list[tuple[str, str]]:
    """'a=1 sample=My File.wav b=2' -> [(a,1),(sample,My File.wav),(b,2)]"""
    body = " ".join(body.split())
    ms = list(OPCODE_RE.finditer(body))
    ops = []
    for i, m in enumerate(ms):
        end = ms[i + 1].start() if i + 1 < len(ms) else len(body)
        ops.append((m.group(1), body[m.end():end].strip()))
    return ops


def parse_sfz(text: str) -> list[tuple[str, list[tuple[str, str]]]]:
    parts = HEADER_RE.split(text)
    blocks = []
    for i in range(1, len(parts), 2):
        blocks.append((parts[i], parse_opcodes(parts[i + 1])))
    return blocks


# ------------------------------------------------------------------ override rules
def overridden(key: str, ours: set[str]) -> bool:
    if key in ours:
        return True
    fam = re.sub(r"_?\d+$", "", key)   # amp_velcurve_64 -> amp_velcurve
    return any(re.sub(r"_?\d+$", "", o) == fam and fam.endswith("velcurve") for o in ours)


def emit(header: str, ops: list[tuple[str, str]]) -> str:
    return f"<{header}>\n" + "".join(f"{k}={v}\n" for k, v in ops)


def flatten(pack_sfz: Path, overrides: Path) -> str:
    root = pack_sfz.parent
    pack = parse_sfz(preprocess(pack_sfz, root, {}))
    ours = parse_sfz(preprocess(overrides, overrides.parent, {}))
    our_global = list({k: (k, v) for h, ops in ours if h == "global" for k, v in ops}.values())  # last wins
    our_control = [kv for h, ops in ours if h == "control" for kv in ops]
    our_keys = {k for k, _ in our_global}

    default_path = ""
    control, glob, body = [], [], []
    for h, ops in pack:
        if h == "control":
            for k, v in ops:
                if k == "default_path":
                    default_path = v.replace("\\", "/")
                else:
                    control.append((k, v))
            continue
        cleaned = []
        for k, v in ops:
            if k == "sample" and not v.startswith("*"):
                v = str((root / default_path / v.replace("\\", "/")).resolve())
            if overridden(k, our_keys):
                continue
            cleaned.append((k, v))
        if h == "global":
            glob.extend(cleaned)
        else:
            body.append((h, cleaned))

    out = [f"// GENERATED by src/render/sfz_prepare.py — edit {overrides.name} instead\n",
           f"// pack: {pack_sfz}\n"]
    out.append(emit("control", control + our_control))
    out.append(emit("global", glob + our_global))
    out += [emit(h, ops) for h, ops in body]
    return "\n".join(out)


# ------------------------------------------------------------------ WAV -> regions (VSCO-2 CE)
WAV_RE = re.compile(r"_([A-Ga-g])([#sb]?)(-?\d)_v(\d+)(?:_(?:rr)?(\d+))?", re.I)


def regions_from_wavs(wav_dir: Path, octave_offset: int = 0) -> str:
    """Map WAV files named like `VlnEns_susVib_F#3_v2_rr1.wav` to SFZ regions.

    octave_offset: VSCO-2 names samples with the C3 = middle-C convention, so
    its `G2` is the violin's open G (MIDI 55) -> use octave_offset=1.
    """
    rows = []
    for f in sorted(wav_dir.glob("*.wav")) + sorted(wav_dir.glob("*.flac")):
        m = WAV_RE.search(f.stem)
        if not m:
            continue
        name, acc, octv, vel, rr = m.groups()
        key = 12 * (int(octv) + 1 + octave_offset) + NOTE_PC[name.lower()] + {"#": 1, "s": 1, "b": -1}.get(acc.lower(), 0)
        rows.append((key, int(vel), int(rr or 1), f.resolve()))
    if not rows:
        raise FileNotFoundError(f"no parsable samples in {wav_dir}")
    keys = sorted({r[0] for r in rows})
    vels = sorted({r[1] for r in rows})
    lo_hi = {}
    for i, k in enumerate(keys):
        lo = 0 if i == 0 else (keys[i - 1] + k) // 2 + 1
        hi = 127 if i == len(keys) - 1 else (k + keys[i + 1]) // 2
        lo_hi[k] = (lo, hi)
    vel_rng = {}
    for i, v in enumerate(vels):
        vel_rng[v] = (1 + i * 127 // len(vels), (i + 1) * 127 // len(vels))
    out = [f"// regions generated from {wav_dir}\n"]
    by_zone: dict[tuple[int, int], list[tuple[int, Path]]] = {}
    for key, vel, rr, path in rows:
        by_zone.setdefault((key, vel), []).append((rr, path))
    for (key, vel), takes in sorted(by_zone.items()):
        lo, hi = lo_hi[key]
        lv, hv = vel_rng[vel]
        takes.sort()
        # round robins only where a zone really has several takes
        # (a global seq_length would mute every 2nd note on single-take zones)
        out.append(f"<group> lokey={lo} hikey={hi} pitch_keycenter={key} lovel={lv} hivel={hv}"
                   + (f" seq_length={len(takes)}" if len(takes) > 1 else "") + "\n")
        for pos, (_, path) in enumerate(takes, start=1):
            out.append(f"<region> sample={path}" + (f" seq_position={pos}" if len(takes) > 1 else "") + "\n")
    return "".join(out)


# ------------------------------------------------------------------ entry
def find_pack_sfz(glob: str) -> Path | None:
    hits = sorted(C.SAMPLES_DIR.glob(glob))
    return hits[0] if hits else None


def prepare(part: str) -> Path | None:
    """Return path of build/sfz/<part>.sfz, or None if samples are missing."""
    src = C.SAMPLE_SOURCES.get(part)
    overrides = C.INSTRUMENTS_DIR / f"{part}.sfz"
    if not src or not overrides.exists():
        return None
    C.SFZ_BUILD_DIR.mkdir(parents=True, exist_ok=True)
    out = C.SFZ_BUILD_DIR / f"{part}.sfz"
    if "sfz_glob" in src:
        pack = find_pack_sfz(src["sfz_glob"])
        if not pack:
            return None
        out.write_text(flatten(pack, overrides))
    else:
        wav_dir = C.SAMPLES_DIR / src["wav_dir"]
        if not wav_dir.is_dir():
            return None
        tmp = C.SFZ_BUILD_DIR / f"{part}_pack.sfz"
        tmp.write_text(regions_from_wavs(wav_dir, src.get("octave_offset", 0)))
        out.write_text(flatten(tmp, overrides))
    return out


def main(argv=None):
    parts = (argv or sys.argv[1:]) or list(C.SAMPLE_SOURCES)
    for p in parts:
        r = prepare(p)
        print(f"[sfz] {p}: {r if r else 'samples missing -> skipped (see README)'}")


if __name__ == "__main__":
    main()
